main:
  params: [args]
  steps:
    - init:
        assign:
          - bigquery_project_id: ${args.bigquery_project_id}
          - ccai_insights_region: ${args.ccai_insights_region}
          - bigquery_dataset: ${args.bigquery_dataset}
          - bigquery_table: ${args.bigquery_table}
    - exportToBigQuery:
        call: http.post
        args:
          url: ${"https://contactcenterinsights.googleapis.com/v1/projects/" + bigquery_project_id + "/locations/" + ccai_insights_region + "/insightsdata:export"}
          headers:
            Content-Type: application/json
          auth:
            type: OAuth2
          body:
            bigQueryDestination:
              projectId: ${bigquery_project_id}
              dataset: ${bigquery_dataset}
              table: ${bigquery_table}
        result: exportToBigqueryResponse
    - logExportToBigqueryResponse:
        call: sys.log
        args:
          data: ${exportToBigqueryResponse.body}
          severity: "INFO" # Optional