main:
  steps:
    - init:
        assign:
          - project_id: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - region: "us-central1"
          - bigquery_dataset: "ccai_insights"
          - bigquery_table: "conversation_analysis"
    - exportToBigQuery:
        call: http.post
        args:
          url: ${"https://contactcenterinsights.googleapis.com/v1/projects/" + project_id + "/locations/" + region + "/insightsdata:export"}
          headers:
            Content-Type: application/json
          auth:
            type: OAuth2
          body:
            bigQueryDestination:
              projectId: ${project_id}
              dataset: ${bigquery_dataset}
              table: ${bigquery_table}
        result: exportToBigqueryResponse
    - logExportToBigqueryResponse:
        call: sys.log
        args:
          data: ${exportToBigqueryResponse.body}
          severity: "INFO" # Optional